apiVersion: v1
kind: Service
metadata:
  name: unified-dashboard-backend
  labels:
    app.kubernetes.io/name: unified-dashboard-backend
spec:
  selector:
    app.kubernetes.io/name: unified-dashboard-backend
  ports:
    - name: http-api
      port: 8081
      targetPort: http-api
  type: ClusterIP
