apiVersion: v1
kind: Service
metadata:
  name: unified-dashboard-frontend
  labels:
    app.kubernetes.io/name: unified-dashboard-frontend
spec:
  selector:
    app.kubernetes.io/name: unified-dashboard-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
